routes/web.php
//            Route::delete('delete/{id}', ['uses' => 'NewsController@delete', 'as' => 'news.delete']);
//        });
//        // testimonials routes
//
//        Route::group(['as' => 'testimonials.', 'prefix' => 'testimonials'], function () {
//
//            Route::get('', ['uses' => 'TestimonialsController@index', 'as' => 'index']);
//            Route::post('add', ['uses' => 'TestimonialsController@add', 'as' => 'add.testimonials']);
//            Route::post('edit', ['uses' => 'TestimonialsController@edit', 'as' => 'edit.testimonials']);
//            Route::delete('delete/{id}', ['uses' => 'TestimonialsController@delete', 'as' => 'testimonials.delete']);
//        });
//
//
//        // orders routes
//
//        Route::group(['as' => 'orders.', 'prefix' => 'orders'], function () {
//
//            Route::get('', ['uses' => 'OrdersController@index', 'as' => 'index']);
//            Route::get('accept/{order}', ['uses' => 'OrdersController@acceptOrder', 'as' => 'accept']);
//            Route::get('cash-back/{order}/details', ['uses' => 'OrdersController@cashBackDetails', 'as' => 'cash.back.details']);
//            Route::patch('cash-back-response', ['uses' => 'OrdersController@cashBackResponse', 'as' => 'cash.back.response']);
//            Route::post('invoice/{order}/download', ['uses' => 'OrdersController@downloadInvoiceDetails', 'as' => 'invoice.download']);
//        });
//
//
//
//
//        //fast orders routes
//
//        Route::group(['as' => 'fast.', 'prefix' => 'fast'], function () {
//
//            Route::get('', ['uses' => 'FastOrdersController@index', 'as' => 'index']);
//            Route::get('accept/fast/{order}', ['uses' => 'FastOrdersController@acceptOrder', 'as' => 'accept']);
//            Route::get('cash-back/fast/{order}/details', ['uses' => 'FastOrdersController@cashBackDetails', 'as' => 'cash.back.details']);
//            Route::patch('cash-back-response', ['uses' => 'FastOrdersController@cashBackResponse', 'as' => 'cash.back.response']);
//            Route::post('invoice/fast/{order}/download', ['uses' => 'FastOrdersController@downloadInvoiceDetails', 'as' => 'invoice.download']);
//        });
//
//
//
//
//        // suggestions routes
//
//        Route::group(['as' => 'suggestions.', 'prefix' => 'suggestions'], function () {
//
//            Route::get('', ['uses' => 'SuggestionsController@index', 'as' => 'index']);
//            Route::delete('suggestion/{id}', ['uses' => 'SuggestionsController@deleteSuggestion', 'as' => 'suggestion.delete']);
//        });
//
//        // notifications routes
//
//        Route::group(['as' => 'notifications.', 'prefix' => 'notifications'], function () {
//
//            Route::get('', ['uses' => 'NotificationsController@index', 'as' => 'index']);
//            Route::post('send-notification', ['uses' => 'NotificationsController@sendNotification', 'as' => 'send']);
//        });
//
//
//        // settings routes
//
//        Route::group(['as' => 'settings.', 'prefix' => 'settings'], function () {
//
//            Route::get('', ['uses' => 'SettingsController@index', 'as' => 'index']);
//            Route::patch('update', ['uses' => 'SettingsController@update', 'as' => 'update']);
//        });
//
//
//        // laundries routes
//
//        Route::group(['as' => 'laundries.', 'prefix' => 'laundries'], function () {
//
//            Route::get('', ['uses' => 'LaundriesController@index', 'as' => 'index']);
//            Route::get('user/{id}/details', ['uses' => 'LaundriesController@userDetails', 'as' => 'user.details']);
//            Route::post('add-owner', ['uses' => 'LaundriesController@add', 'as' => 'add']);
//            Route::post('edit-owner', ['uses' => 'LaundriesController@edit', 'as' => 'edit']);
//            Route::patch('toggle-status', ['uses' => 'LaundriesController@toggleStatus', 'as' => 'toggle.status']);
//            Route::patch('laundry-toggle-status', ['uses' => 'LaundriesController@laundryToggleStatus', 'as' => 'laundry.toggle.status']);
//            Route::delete('delete-owner/{id}', ['uses' => 'LaundriesController@delete', 'as' => 'user.delete']);
//            Route::post('edit-laundry/{id}', ['uses' => 'LaundriesController@editLaundry', 'as' => 'edit.laundry']);
//            Route::post('fees/{id}/reset', ['uses' => 'LaundriesController@feesReset', 'as' => 'fees.reset']);
//            Route::post('add-service', ['uses' => 'LaundriesController@addService', 'as' => 'add.service']);
//            Route::post('edit-service', ['uses' => 'LaundriesController@editService', 'as' => 'edit.service']);
//            Route::delete('delete-service/{id}', ['uses' => 'LaundriesController@deleteService', 'as' => 'service.delete']);
//        });
//
//        // notifications routes
//
//        Route::group(['as' => 'cities.', 'prefix' => 'cities'], function () {
//
//            Route::get('', ['uses' => 'CitiesController@index', 'as' => 'index']);
//            Route::post('add', ['uses' => 'CitiesController@add', 'as' => 'add']);
//            Route::post('edit/{id}', ['uses' => 'CitiesController@edit', 'as' => 'edit']);
//            Route::delete('delete/{id}', ['uses' => 'CitiesController@delete', 'as' => 'delete']);
//        });
//    });
//});
//
//
///**
// * Laundry Owners Routes
// **/
//
//Route::group(['namespace' => 'Laundry', 'prefix' => 'laundry', 'as' => 'laundry.'], function () {
//
//    // auth routes
//
//    Route::group(['as' => 'auth.', 'prefix' => 'auth'], function () {
//
//        Route::get('', ['uses' => 'AuthController@index', 'as' => 'index']);
//        Route::post('login', ['uses' => 'AuthController@login', 'as' => 'login']);
//        Route::get('logout', ['uses' => 'AuthController@logout', 'as' => 'logout']);
//    });
//
//    Route::group(['middleware' => 'Laundry'], function () { // adding the admin middleware to all the routes except the auth
//
//        Route::prefix('messenger')->group(function () {
//            Route::get('t/{id}', 'MessageController@laravelMessenger')->name('messenger');
//            Route::post('send', 'MessageController@store')->name('message.store');
//            Route::get('threads', 'MessageController@loadThreads')->name('threads');
//            Route::get('more/messages', 'MessageController@moreMessages')->name('more.messages');
//            Route::delete('delete/{id}', 'MessageController@destroy')->name('delete');
//            // AJAX requests.
//            Route::prefix('ajax')->group(function () {
//                Route::post('make-seen', 'MessageController@makeSeen')->name('make-seen');
//            });
//        });
//        // dashboard routes
//
//        Route::group(['as' => 'dashboard.'], function () {
//
//            Route::get('', ['uses' => 'DashboardController@index', 'as' => 'index']);
//            Route::get('read-notification', ['uses' => 'DashboardController@readNotification', 'as' => 'read.notification']);
//            Route::get('new-notification', ['uses' => 'DashboardController@newNotification', 'as' => 'new.notification']);
//        });
//
//        // profile routes
//
//        Route::group(['as' => 'profile.', 'prefix' => 'profile'], function () {
//
//            Route::get('', ['uses' => 'ProfileController@index', 'as' => 'index']);
//            Route::patch('update-information', ['uses' => 'ProfileController@updateInfo', 'as' => 'update.info']);
//            Route::patch('update-password', ['uses' => 'ProfileController@updatePassword', 'as' => 'update.password']);
//        });
//
//
//        // laundries routes
//
//        Route::group(['as' => 'laundries.', 'prefix' => 'laundries'], function () {
//
//            Route::get('', ['uses' => 'LaundriesController@index', 'as' => 'index']);
//            Route::get('user/{id}/details', ['uses' => 'LaundriesController@userDetails', 'as' => 'user.details']);
//            Route::post('add-owner', ['uses' => 'LaundriesController@add', 'as' => 'add']);
//            Route::post('edit-owner', ['uses' => 'LaundriesController@edit', 'as' => 'edit']);
//            Route::patch('toggle-status', ['uses' => 'LaundriesController@toggleStatus', 'as' => 'toggle.status']);
//            Route::delete('delete-owner/{id}', ['uses' => 'LaundriesController@delete', 'as' => 'user.delete']);
//            Route::post('edit-laundry/{id}', ['uses' => 'LaundriesController@editLaundry', 'as' => 'edit.laundry']);
//            Route::post('fees/{id}/reset', ['uses' => 'LaundriesController@feesReset', 'as' => 'fees.reset']);
//            Route::post('invoice/{order}/download', ['uses' => 'LaundriesController@downloadInvoiceDetails', 'as' => 'invoice.download']);
//            Route::post('add-service', ['uses' => 'LaundriesController@addService', 'as' => 'add.service']);
//            Route::post('edit-service', ['uses' => 'LaundriesController@editService', 'as' => 'edit.service']);
//            Route::delete('delete-service/{id}', ['uses' => 'LaundriesController@deleteService', 'as' => 'service.delete']);
//        });
//    });
//});






Route::group(['prefix'=>'login','namespace'=>'Backend\Authentication'], function (){
    Route::group(['prefix'=>'admin'],function () {
        Route::get('', 'AuthenticationController@index')->name('login');
        Route::post('auth', 'AuthenticationController@login')->name('user.login');
    });

});

Route::group(['prefix'=>'admin',['middleware' => 'Admin'],'namespace'=>'Backend\Dashboard'], function () {

    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('', 'DashboardController@index')->name('dashboard');
        Route::post('', 'DashboardController@logout')->name('logout');
    });


        Route::group(['prefix' => 'users'], function () {

            Route::get('','UsersController@index')->name('users');
            Route::get('user/{id}/details','UsersController@userDetails')->name('users.details');
            Route::post('toggle-status','UsersController@toggleStatus')->name('users.status');

app/Order.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use SoftDeletes;
    protected $casts = [
        'services_id' => 'array',
        'services_name' => 'array',
        'services_name_en' => 'array',
        'services_type' => 'array',
        'services_count' => 'array',
        'services_price' => 'array',
    ];
    protected $fillable = [

        'services_id',
        'laundry_id',
        'services_name',
        'services_name_en',
        'services_type',
        'services_count',
        'services_price',
        'delegate_id',
        'order_status',
        'city',
        'delivery',
        'address',
        'user_id',
        'reason',
        'lat',
        'lng',
        'payment_type',
        'is_paid',
        'is_collected',
        'order_type',
        'description',
        'estimate_time'
    ];
    protected $appends = [
        'order_total'
    ];

    public function getDelegateIdAttribute($value)
    {
        return $value ? $value : 0;
    }
    
    

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->toDateString();
    }

    public function getReasonAttribute($value)
    {
        return $value ? $value : "";
    }
    
   

    public function getOrderTotalAttribute($value)
    {
        if($this->services_id!=0)
        {
        return array_sum($this->services_price) + intval($this->delivery);
        }else{
            return 0;
        }
            
        }

    public function getOrderServices()
    {
        $services = [];
        $count = count(array($this->services_id));
        

         if($this->services_id!=0){
         for ($i = 0 ; $i < $count ; $i++) {
            $service = LaundryServices::find($this->services_id[$i]);
            //dd($this->services_price[$i]);
            $data = [
                'service_id' => $this->services_id[$i],
                'service_name' => app()->isLocale('ar') ?  $this->services_name[$i] : $this->services_name_en[$i],
                'service_type' => $this->services_type[$i],
                'service_count' => $this->services_count[$i],
                'service_price' => $this->services_price[$i],
                'img' => $service ? $service->img : "",
                'service_total' => $this->services_price[$i] * $this->services_count[$i],
            ];
            array_push($services, $data);
         }
             
         }else{
             return [];
         }
        return $services;
         
    }

    public function laundry()
    {
        return $this->belongsTo(Laundry::class, 'laundry_id');
    }


    public function service($id)
    {
        return LaundryServices::find($id);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function chat()
    {
        return $this->hasOne(Chat::class);
    }

    public function delegate()
    {
        return $this->belongsTo(Delegate::class)->withDefault();
    }

    public function totalPrice()
    {
        //return array_sum($this->services_price) + intval($this->delivery);
          if($this->services_id!=0)
        {
        return array_sum($this->services_price) + intval($this->delivery);
        }else{
            return 0;
        }
    }

    public function servicePrice()
    {
        return array_sum($this->services_price);
    }

    public function rate()
    {
        return $this->hasOne(Rate::class, 'order_id');
    }
    
    
    public function getEstimatedTimeAttribute($value)
    {
        return Carbon::parse($value)->toDateString();
    }

}

app/Http/Controllers/Api/LaundryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Resources\Laundries\LaundriesResourceCollection;
use App\Laundry;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LaundryController extends Controller
{

    public function index(Request $request)
    {
        $per_page = $request->per_page ? $request->per_page : 5;
        $laundries = Laundry::where('is_active', 1)->where('expire_date', '>=', Carbon::today())
            ->when($request->has_offer, function ($laundry) {
                return $laundry->where('has_offers', 1);
            })->when($request->lat && $request->lng, function ($laundry) use ($request) {
                return $laundry->orderByRaw("( 6371 * acos ( cos ( radians(" . $request->lat . ") ) * cos( radians( lat ) ) * cos( radians( lng ) - radians(" . $request->lng . ") ) + sin ( radians(" . $request->lat . ") ) * sin( radians( lat ) ) ) <= 50) desc" );
            })
            ->get();
        return apiResponse(200, 'المغاسل', new LaundriesResourceCollection($laundries), true, $per_page);
    }

}

app/Http/Controllers/Laundry/AuthController.php
<?php

namespace App\Http\Controllers\Laundry;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{


    public function index()
    {
        return view('laundry.pages.auth.index');
    }

    public function login(Request $request)
    {
        $this->validate($request, [
            'email' => 'required',
            'password' => 'required'
        ], [
            'email.required' => 'برجاء إدخال البريد الإلكترونى',
            'password.required' => 'برجاء إدخال كلمه المرور'
        ]);
        if (\Auth::guard('laundry')->attempt(['email'=>$request->email,'password'=>$request->password]))

        {
            return redirect()->route('laundry.dashboard.index');

        }
        elseif (\Auth::guard('laundry')->attempt(['name'=>$request->email,'password'=>$request->password]))
        {
            return redirect()->route('laundry.dashboard.index');

        }
        return redirect()->route('laundry.auth.index')->withInput($request->all())->exceptInput($request->password)->withErrors('برجاء التأكد من إسم المستخدم وكلمه المرور');
    }

    public function logout(){
        auth()->guard('laundry')->logout();
        return redirect()->route('laundry.auth.index');
    }
}

app/Http/Controllers/Site/LaundryController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Laundry;
use Illuminate\Support\Carbon;

class LaundryController extends Controller
{
    public function index()
    {
        $laundries = Laundry::where('is_active', 1)->where('expire_date', '>=', Carbon::today())->get();
        return view('site.pages.laundry',compact('laundries'));
    }
    public function details(Laundry $laundry)
    {
       return view('site.pages.laundry-details', compact('laundry'));
    }
}

resources/views/laundry/layouts/footer.blade.php
<footer class="br-footer">
    <div class="footer-center">
        <div class="mg-b-2">
            <a target="_blank" href="http://2grand.net/">
                <img style="max-width: 15% !important;" src="{{url('android.png')}}" class="grand3">
            </a>
            Copyright &copy; 2019.
        </div>

    </div>
    <div class="footer-right d-flex align-items-center">
        <span class="tx-uppercase mg-r-10">Share:</span>
        <a target="_blank" class="pd-x-5" href="https://www.facebook.com/sharer/sharer.php?u=http%3A//themepixels.me/bracket/intro"><i class="fa fa-facebook tx-20"></i></a>
        <a target="_blank" class="pd-x-5" href="https://twitter.com/home?status=Bracket,%20your%20best%20choice%20for%20premium%20quality%20admin%20template%20from%20Bootstrap.%20Get%20it%20now%20at%20http%3A//themepixels.me/bracket/intro"><i class="fa fa-twitter tx-20"></i></a>
    </div>
</footer>

resources/views/laundry/layouts/header.blade.php
<!-- ########## START: HEAD PANEL ########## -->
<div class="br-header">
    <div class="br-header-left">

        <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a>
        </div>
        <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a>
        </div>

    </div><!-- br-header-left -->
    <a target="_blank" href="http://2grand.net/" style="margin: 0 auto">
        <img style="max-width: 15% !important; " src="{{asset('/android.png')}}" class="grand">
    </a>
    <div class="br-header-right">
        <div class="dropdown">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
                <i class="icon ion-ios-email-outline tx-24"></i>
                <!-- start: if statement -->
                @if ((count(laundryMessagesNotification())))
                    <span class="square-8 bg-danger pos-absolute t-15 r-5 rounded-circle"></span>
            @endif
            <!-- end: if statement -->
            </a>
            <div class="dropdown-menu dropdown-menu-header wd-300 pd-0-force notifications">
                <div class="d-flex align-items-center justify-content-between pd-y-10 pd-x-20 bd-b bd-gray-200">
                    <label class="tx-12 tx-info tx-uppercase tx-semibold tx-spacing-2 mg-b-0">الرسائل</label>
                    @if (count(laundryMessagesNotification()))
                        <a href="{{route('laundry.dashboard.read.notification',['type'=>'message'])}}"><label
                                    class="tx-12 tx-info tx-uppercase tx-semibold tx-spacing-2 mg-b-0">قرأه
                                الكل</label></a>
                    @endif

                </div><!-- d-flex -->
                <div style="overflow:auto; height: 210px">
                    <div class="media-list infinite-scroll">
                    @if ((count(laundryMessagesNotification())))
                        @foreach(laundryMessagesNotification() as $notification)
                            <!-- loop starts here -->
                                <a href="{{route('laundry.messenger',['id'=>$notification->data['user_id'],'notification_id'=>$notification->id])}}"
                                   class="media-list-link read notification">
                                    <div class="media pd-x-20 pd-y-15">
                                        <div class="media-body">
                                            <p class="tx-13 mg-b-0 tx-gray-700"> {{$notification->data['message']}}
                                                من &nbsp;{{$notification->data['user_name']}}</p>
                                            <span class="tx-12">{{$notification->created_at->diffForHumans()}}</span>
                                        </div>
                                    </div><!-- media -->
                                </a>
                                <!-- loop ends here -->
                            @endforeach
                        @else
                            <div class="pd-y-10 tx-center bd-t">
                                <a href="#" class="tx-12"> لا يوجد رسائل جديده</a>
                            </div>
                        @endif
                        {{--                        {{adminNotification()->links()}}--}}
                    </div><!-- media-list -->
                    {{--  @if (adminNotification()->total() > 3)
                          <div class="pd-y-10 tx-center bd-t">
                              <button class="view-more form-control" style="width: 30% ; display: table;margin: 0 auto;">
                                  المزيد
                              </button>
                          </div>
                      @endif--}}
                </div>
            </div><!-- dropdown-menu -->
        </div><!-- dropdown -->
        <div class="dropdown">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
                <i class="icon ion-ios-bell-outline tx-24"></i>
                <!-- start: if statement -->
                @if ((count(laundryNotification())))   <span
                        class="square-8 bg-danger pos-absolute t-15 r-5 rounded-circle"></span>
            @endif
            <!-- end: if statement -->
            </a>
            <div class="dropdown-menu dropdown-menu-header wd-300 pd-0-force notifications">
                <div class="d-flex align-items-center justify-content-between pd-y-10 pd-x-20 bd-b bd-gray-200">
                    <label class="tx-12 tx-info tx-uppercase tx-semibold tx-spacing-2 mg-b-0">الإشعارات</label>
                    @if (count(laundryNotification()))
                        <a href="{{route('laundry.dashboard.read.notification')}}"><label
                                    class="tx-12 tx-info tx-uppercase tx-semibold tx-spacing-2 mg-b-0">قرأه
                                الكل</label></a>
                    @endif
                </div><!-- d-flex -->
                <div style="overflow:auto; height: 210px">
                    <div class="media-list infinite-scroll">
                    @if ((count(laundryNotification())))
                        @foreach(laundryNotification() as $notification)
                            <!-- loop starts here -->
                                <a href="{{route('laundry.dashboard.read.notification',['id'=>$notification->id])}}"
                                   class="media-list-link read notification">
                                    <div class="media pd-x-20 pd-y-15">
                                        <div class="media-body">
                                            <p class="tx-13 mg-b-0 tx-gray-700"> {{$notification->data['message']}}
                                                &nbsp; #{{$notification->data['order_id']}}</p>
                                            <span class="tx-12">{{$notification->created_at->diffForHumans()}}</span>
                                        </div>
                                    </div><!-- media -->
                                </a>
                                <!-- loop ends here -->
                            @endforeach
                        @else
                            <div class="pd-y-10 tx-center bd-t">
                                <a href="#" class="tx-12"> لا يوجد إشعارات جديده</a>
                            </div>
                        @endif
{{--                        {{laundryNotification()->links()}}--}}
                    </div><!-- media-list -->
                    {{--@if (laundryNotification()->total() > 3)
                        <div class="pd-y-10 tx-center bd-t">
                            <button class="view-more form-control" style="width: 30% ; display: table;margin: 0 auto;">
                                المزيد
                            </button>
                        </div>
                    @endif--}}
                </div>
            </div><!-- dropdown-menu -->
        </div><!-- dropdown -->
        <nav class="nav">
            <div class="dropdown">
                <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
                    <span class="logged-name hidden-md-down">
                        {{ auth()->guard('laundry')->user()->name }}
                    </span>
                    <img src="{{auth()->guard('laundry')->user()->img ? asset('uploads/profile/' . auth()->guard('laundry')->user()->img) : 'http://via.placeholder.com/64x64'}}  "
                         class="wd-32 rounded-circle" alt="">
                    <span class="square-10 bg-success"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-header wd-200">
                    <ul class="list-unstyled user-profile-nav">
                        <li><a href="{{route('laundry.profile.index')}}"><i class="icon ion-ios-person"></i> الصفحه
                                الشخصيه</a>
                        </li>
                        <li><a href="{{ route('laundry.auth.logout') }}"><i class="icon ion-power"></i> تسجيل الخروج</a>
                        </li>
                    </ul>
                </div><!-- dropdown-menu -->
            </div><!-- dropdown -->
        </nav>

{{--         <div class="navicon-right">--}}
{{--            <a id="btnRightMenu" href="" class="pos-relative">--}}
{{--                <i class="icon ion-ios-chatboxes-outline"></i>--}}
{{--                <!-- start: if statement -->--}}
{{--                <span class="square-8 bg-danger pos-absolute t-10 r--5 rounded-circle"></span>--}}
{{--                <!-- end: if statement -->--}}
{{--            </a>--}}
{{--        </div><!-- navicon-right -->--}}
    </div><!-- br-header-right -->
</div><!-- br-header -->
<!-- ########## END: HEAD PANEL ########## -->

resources/views/laundry/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@yield('title')</title>
    <!-- compiled css -->
    <link href="{{ asset('css/admin.css')}}" media="all" rel="stylesheet" type="text/css"/>
    <meta name="csrf-token" content="{{@csrf_token()}}">
    @yield('styles')

</head>

<body>

<!-- ########## START: LEFT PANEL ########## -->
@include('laundry.layouts.navigation')
<!-- ########## END: LEFT PANEL ########## -->

<!-- ########## START: HEAD PANEL ########## -->
<div id="notifications">
    @include('laundry.layouts.header')
</div>
<!-- ########## END: HEAD PANEL ########## -->


<!-- ########## START: MAIN PANEL ########## -->
<div class="br-mainpanel" style="direction: rtl">
    @yield('content')
    @include('laundry.layouts.footer')
</div><!-- br-mainpanel -->
@include('laundry.pages.modals.modals')
<!-- ########## END: MAIN PANEL ########## -->
<script type="text/javascript" src="{{asset('js/admin.js')}}"></script>

<script>

    setTimeout(fade_out, 5000);

    function fade_out() {
        $("#validation").fadeOut().empty();
    }

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

</script>
<script src="https://js.pusher.com/4.4/pusher.min.js"></script>
@yield('scripts')
<script>
    // Enable pusher logging - don't include this in production
    /*Pusher.logToConsole = true;*/
    var pusher = new Pusher("{{env('PUSHER_APP_KEY')}}", {
        cluster: 'eu',
        forceTLS: true
    });
    var channel2 = pusher.subscribe('new-message');
    channel2.bind('new-message', (e) => {
        $.ajax({
            url: '{{route('laundry.dashboard.new.notification')}}',
            type: 'get',
            data: {_toke: '{{csrf_token()}}'},
            success: function (response) {
                $('#notifications').html(response.view);
            },
            error: function () {
                alert('error');
            }
        });
    });
    var channel = pusher.subscribe('new-order');
    channel.bind('new-order', (e) => {
        $.ajax({
            url: '{{route('laundry.dashboard.new.notification')}}',
            type: 'get',
            data: {_toke: '{{csrf_token()}}'},
            success: function (response) {
                $('#notifications').html(response.view);
            },
            error: function () {
                alert('error');
            }
        });
    });
</script>
{{--<script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.js"></script>

<script type="text/javascript">
    $('ul.pagination').hide();
    $('.infinite-scroll').infiniteScroll({
        // options
        path: '.pagination li.active + li a',
        append: '.notification',
        history: false,
        checkLastPage: true,
        button: '.view-more',
// load pages on button click
        scrollThreshold: false,
// disable loading on scroll

    });
    $('.dropdown-menu').click(function (e) {
        e.stopPropagation();
    });
</script>--}}

</body>
</html>

resources/views/laundry/layouts/navigation.blade.php
<div class="br-logo">
    <a target="_blank" href="http://2grand.net/">
        <span>
        <img style="max-width: 90% !important;" src="{{asset('/android.png')}}" class="grand">
        </span>
    </a>
</div>
<div class="br-sideleft overflow-y-auto">
    <label class="sidebar-label pd-x-15 mg-t-20" style="direction: rtl">القائمه الرئيسيه</label>
    <div class="br-sideleft-menu">
        <a href="{{route('laundry.dashboard.index')}}"
           class="br-menu-link {{sidebarActive(['laundry.dashboard.index'])}}">
            <div class="br-menu-item">
                <i class="menu-item-icon icon ion-ios-home-outline tx-22"></i>
                <span class="menu-item-label">الرئيسيه</span>
            </div><!-- menu-item -->
        </a><!-- br-menu-link -->

        <a href="{{route('laundry.laundries.user.details' , auth('laundry')->id())}}"
           class="br-menu-link {{sidebarActive(['laundry.laundries.user.details'])}}">
            <div class="br-menu-item">
                <i class="menu-item-icon icon ion-ios-person-outline tx-24"></i>
                <span class="menu-item-label"> المغسله</span>
            </div><!-- menu-item -->
        </a><!-- br-menu-link -->


        <a href="{{route('laundry.messenger',1)}}" class="br-menu-link {{sidebarActive(['laundry.messenger'])}}">
            <div class="br-menu-item">
                <i class="menu-item-icon icon ion-chatbox tx-24"></i>
                <span class="menu-item-label"> المحادثات </span>
            </div><!-- menu-item -->
        </a><!-- br-menu-link -->

    </div><!-- br-sideleft-menu -->

</div><!-- br-sideleft -->